---
zabbix_frontend_db_type: POSTGRESQL
zabbix_frontend_db_port: 5432
zabbix_frontend_db_host: 127.0.0.1
zabbix_frontend_db_name: zabbix
zabbix_frontend_db_user: zabbix
zabbix_frontend_db_password: change_me
zabbix_frontend_server_name: Zabbix
zabbix_frontend_server_host: 127.0.0.1
zabbix_frontend_web_root: /etc/zabbix/web
zabbix_frontend_packages_debian:
  - zabbix-frontend-php
  - zabbix-apache-conf
  - php-pgsql
  - apache2
zabbix_frontend_packages_rhel:
  - zabbix-web-pgsql
  - zabbix-web-service
  - httpd
  - php-pgsql
zabbix_frontend_web_service: "{{ (ansible_os_family == 'Debian') | ternary('apache2', 'httpd') }}"
